# Atuin configuration
# https://atuin.sh/docs/config

## where to store the database
# db_path = "~/.local/share/atuin/history.db"

## where to store the session file
# session_path = "~/.local/share/atuin/session"

## date format for the history list
## there's also a "relative" setting, which will show "5m ago", etc
# date_format = "%Y-%m-%d %H:%M:%S"

## whether or not to use the filter mode by default
## "global", "host", "session", "directory"
# filter_mode = "global"

## search mode
## "prefix", "fulltext", "fuzzy", "skims"
# search_mode = "fuzzy"

## exit mode
## "return-query", "return-original"
# exit_mode = "return-original"

## sync configuration
auto_sync = false
update_check = false

## keymap
# keymap_mode = "emacs"

## style
# style = "compact"

## inline height
inline_height = 10

## show help
# show_help = true
