[window]
decorations = "None"
padding = { x = 10 , y = 10}

[font]
size = 21
normal = { family = "JetBrainsMono NF", style = "Regular" }
bold = { family = "JetBrainsMono NF", style = "Bold" }
italic = { family = "JetBrainsMono NF", style = "Italic" }

[cursor]
style = { shape = "Underline", blinking = "Always" }

[hints]
[[hints.enabled]]
binding = { key = 'U', mods = 'Control|Shift' }
mouse = { enabled = true, mods = 'Control' }
regex = "(https|http|ftp)://[\\w\\d\\-./?=#&_~%]+"
action = "Copy"
post_processing = true
command = "open"

[mouse]
bindings = [
    { mouse = "Right", action = "Copy" }
]

[general]
import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/latte.toml"
# "~/.config/alacritty/dawnfox.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]
