[env]
TERM_PROGRAM = "alacritty"

[window]
decorations = "None"
padding = { x = 10 , y = 10}

[font]
size = 18
normal = { family = "JetBrainsMono NF", style = "Regular" }
bold = { family = "JetBrainsMono NF", style = "Bold" }
italic = { family = "JetBrainsMono NF", style = "Italic" }
offset = { x = 0, y = 3 }

[cursor]
style = { shape = "Underline", blinking = "Always" }

[hints]
[[hints.enabled]]
binding = { key = 'U', mods = 'Control|Shift' }
mouse = { enabled = true, mods = 'Control' }
regex = "(https|http|ftp)://[\\w\\d\\-./?=#&_~%]+"
action = "Copy"
post_processing = true
command = "open"

[mouse]
bindings = [
    { mouse = "Right", action = "Copy" }
]

[general]
import = ["~/.config/alacritty/themes/kanagawa-dragon.toml"]

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001bb"   # ESC + b → move word-left

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001bf"   # ESC + f → move word-right

